### ISSUE TITLE
[BUG] Payment records show invoice by default

### ISSUE THREAD

**Issue by aceschen** [calblueprint/meepanyar#112] opened 2021-04-18 01:18 UTC
**Describe the bug**
When opening the payment records, it shows the invoices instead of the payments. 

**To Reproduce**
1. Go to customers
2. Select any customer
3. Click "View All" next to Payment 

**Expected behavior**
Expect for it to open the Payment tab of the records screen instead of the Invoices tab.

**Device (please complete the following information):**
 - Device Model: Pixel 2
 - OS: Android 11

CC: @julianrkung

**Comment by julianrkung** [comment] 2021-04-22 03:26
Closing as duplicate of https://github.com/calblueprint/meepanyar/issues/120

**Closed as completed by julianrkung** 2021-04-22 03:26 UTC
Labels: bug
